# Compose file for local dev, not for prod

version: '2'
services:
  adminpanel:
    build: 
      context: wappuapp-adminpanel
      dockerfile: Dockerfile.dev
    environment:
      BACKEND_URI: backend:80
    ports:
      - "3001:80"
    links:
      - backend

  backend:
    build: 
      context: wappuapp-backend
      dockerfile: Dockerfile.dev
    command: [npm, run, start]
    ports:
      - "9000:80"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://wappu:wappu@database/wappuapp
      - DEFAULT_EVENT_RADIUS=0.400
    volumes:
      - ./wappuapp-backend/src:/app/src
    links:
      - database
      - redis
    
  database:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_DB=wappuapp
      - POSTGRES_USER=wappu
      - POSTGRES_PASSWORD=wappu
    ports:
      - "4432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    ports:
      - "2345:2345"
    volumes:
      - redis_data:/data

volumes:
  database:
    driver: local
  redis_data:
